// const PAYMENT_PROCESSING = "PAYMENT_PROCESSING";
export const INITIATE_PAYMENT = "INITIATE_PAYMENT";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
export const RESET_PAYMENT = "RESET_PAYMENT";
export const PAYMENT_COMPLETE = "PAYMENT_COMPLETE";