// Options for sidebar filters types
export const SIDEBAR_FILTERS_REQUEST = "SIDEBAR_FILTERS_REQUEST";
export const SIDEBAR_FILTERS_SUCCESS = "SIDEBAR_FILTERS_SUCCESS";
export const SIDEBAR_FILTERS_FAILURE = "SIDEBAR_FILTERS_FAILURE";

