// Filtered products types
export const FILTERED_CATEGORY_REQUEST = "FILTERED_CATEGORY_REQUEST";
export const FILTERED_CATEGORY_SUCCESS = "FILTERED_CATEGORY_SUCCESS";
export const FILTERED_CATEGORY_FAILURE = "FILTERED_CATEGORY_FAILURE";

